### ISSUE TITLE
Howler Plugins

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org-legacy#265]
Currently we import at least one howler plugin we don't use (sparcial audio).

This goes back to this upstream issue:
https://github.com/goldfire/howler.js/issues/971

We should keep on eye on that and update the library if it's fixed.

**Comment by Friksel** [comment]
As you mentioned in your post, already in 2018 I asked for this simple change ( goldfire/howler.js#971 ). Because who in the world needs a spatial plugin to be available all the time in code without being used? The issue was marked by the dev for the 2.1.0 milestone, but we are now in version 2.1.4 and it's still not changed. And we never got any reaction on these questions here by the developer.

I think it's pretty bad this developer just ignores its users for so long and don't even take a minute to even respond to its users after so many years.

I am going to look for an alternative now.

**Comment by 0xdevalias** [comment]
Unsure if this is still relevant to your needs, but I just added a comment on the upstream thread with examples of how to import individually: https://github.com/goldfire/howler.js/issues/971#issuecomment-613852758

**Comment by elbotho** [comment]
@0xdevalias what a service! Just saw your comment over there.
Thank you, we will check it out.

@Entkenntnis if you work on implementing the exercises and stumble upon this, check out the thread.

**Comment by elbotho** [comment]
Current developement is happening in [frontend](https://github.com/serlo/frontend). Won't fix here.
