### ISSUE TITLE
Find replacement for algebra.js

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-legacy#492]
The project https://github.com/nicolewhite/algebra.js which we use to compare algebraic expressions was archived by the owner. Thus we shall look for a replacement.

**Comment by inyono** [comment]
Last time I checked (a couple of years ago), there was no suitable alternative that covered our current use cases as well as algebra.js. I'm fine with switching to something better / actively developed but IMHO it's also fine to stick to algebra.js since we only use it one place and there's no security issue related to it. Quickly glancing at the source code, it also looks fine and - if needed at some point - we could easily fork it or move the source code into this repo directly.

**Comment by elbotho** [comment]
Still using algebra.js in the frontend without apparent problems so far.
